stages:
  - build
  - deploy
  - cleanup

.base_werf: &base_werf
  - type trdl && . $(trdl use werf 1.2 ea)
  - type werf && source $(werf ci-env gitlab --as-file --platform linux/amd64)
  - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${WERF_REPO}

Build and Publish:
  stage: build
  script:
    - *base_werf
    - werf build --platform linux/amd64
  except:
    - schedules
  tags:
    - briolink-devops

.base_deploy: &base_deploy
  stage: deploy
  script:
    - *base_werf
    - werf converge --skip-build --set "env_url=$(echo ${CI_ENVIRONMENT_URL} | cut -d / -f 3)" --platform linux/amd64
  dependencies:
    - Build and Publish
  tags:
    - briolink-devops

Deploy to Test:
  <<: *base_deploy
  environment:
    name: test
    url: https://search-service.test.briolink.net
  only:
    - test

Deploy to Development:
  <<: *base_deploy
  environment:
    name: dev
    url: https://search-service.dev.briolink.net
  only:
    - dev

Cleanup:
  stage: cleanup
  script:
    - *base_werf
    - werf cleanup --platform linux/amd64
  only:
    - schedules
  tags:
    - briolink-devops
