logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8100
  error:
    include-stacktrace: never
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/dev_search
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.dev.briolink.com/realms/briolink/protocol/openid-connect/certs
location-service:
  api:
    url: http://kravchuck.ddns.net:70/
    version: 1
