server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  profiles:
    active: ${env.spring_profiles_active:local}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/${env.spring_profiles_active}_search
    username: ${env.DB_USER:ok}
    password: ${env.DB_PASSWORD:ok}
    hikari:
      idle-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        metadata_builder_contributor: com.briolink.searchservice.common.jpa.Functions
    generate-ddl: false
    show-sql: false
  liquibase:
    change-log: migration/master.yml
cloud:
  aws:
    stack:
      auto: false
dgs:
  graphql:
    path: /
app:
  app-endpoints:
    locationservice: http://location-service.${env.spring_profiles_active}.svc.cluster.local/