object Versions {
    const val SPRING_DOTENV = "2.3.0"
    const val POSTGRESQL = "42.3.1"
    const val JAVA = "11"
    const val KOTLIN = "1.5.31"
    const val SPRING_BOOT = "2.5.5"
    const val BLAZE_PERSISTENCE = "1.6.3"
    const val SPRING_DEPENDENCY_MANAGEMENT = "1.0.11.RELEASE"
    const val AWSPRING_CLOUD = "2.3.2"
    const val DGS_CODEGEN = "5.0.6"
    const val SPOTLESS = "5.14.1"
    const val KOTLIN_LOGGING_JVM = "2.0.11"
    const val HIBERNATE_TYPES_55 = "2.12.1"
    const val IBM_ICU4J = "69.1"
    const val LIQUIBASE_CORE = "4.4.3"
    const val MAPSTRUCT = "1.4.2.Final"
    const val BRIOLINK_EVENT = "0.3.2-SNAPSHOT"
    const val JACKSON_MODULE = "2.13.0-rc2"
}
