object Versions {
    const val JAVA = "11"
    const val KOTLIN = "1.6.10"
    const val SPRING_BOOT = "2.6.4"
    const val SPRING_DEPENDENCY_MANAGEMENT = "1.0.11.RELEASE"
    const val AWSPRING_CLOUD = "2.4.0"
    const val DGS_CODEGEN = "5.1.17"
    const val SPOTLESS = "6.3.0"
    const val KOTLIN_LOGGING_JVM = "2.1.21"
    const val HIBERNATE_TYPES_55 = "2.14.0"
    const val IBM_ICU4J = "70.1"
    const val LIQUIBASE_CORE = "4.8.0"
    const val MAPSTRUCT = "1.4.2.Final"
    const val BRIOLINK_EVENT = "0.4.0-SNAPSHOT"
    const val BRIOLINK_LOCATION = "0.2.2-SNAPSHOT"
    const val BRIOLINK_SYNC = "0.2.0-SNAPSHOT"
    const val SPRING_DOTENV = "2.4.1"
    const val BLAZE_PERSISTENCE = "1.6.6"
}
