server:
  port: 8105
  error:
    include-stacktrace: always
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/dev_search
location-service:
  api:
    url: http://192.168.0.60:8070/
    version: 1
sync-service:
  api:
    url: http://192.168.0.60:8400/
    version: 1
